services:
  front:
    image: realworld-frontend
    ports:
      - '8080:80'
    depends_on:
      - back
  back:
    image: realworld-backend
    env_file:
      - .env.back
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    env_file:
      - .env.bd
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "realworld"]
      interval: 5s
      timeout: 5s
      retries: 8
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
