name: Liberar y desplegar la aplicaci贸n

on: push
  # release:
  #   types: [ published ]

jobs:
  test1:
    name: Test 1
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Iniciar sesi贸n en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Compilar imagen y subir a Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          tags: ${{ secrets.DOCKER_USERNAME }}/realworld-backend
  test2:
    name: Test 2
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Iniciar sesi贸n en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Compilar imagen y subir a Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          tags: ${{ secrets.DOCKER_USERNAME }}/realworld-frontend
  test:
    name: Desplegar la aplicaci贸n
    runs-on: ubuntu-latest
    needs:
      - test1
      - test2
    steps:
      - name: Desplegar por SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            if [ ! -d "realworld-antar" ]; then
              git clone https://github.com/${{ github.repository }}.git realworld-antar -b ${{ github.ref_name }}
            fi

            cd realworld-antar
            git switch ${{ github.ref_name }}
            git pull

            docker compose pull
            docker compose up -d