name: Liberar y desplegar imágenes de Docker

on:
    release:
        types: [ published ]

jobs:
    docker-frontend:
        runs-on: ubuntu-latest
        steps:
            - name: Clonar repositorio
              uses: actions/checkout@v4
            - name: Iniciar sesión en Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Extraer metadatos
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: antarespadas/realworld-frontend
            - name: Compilar y subir imagen
              uses: docker/build-push-action@v6
              with:
                context: ./frontend
                tags: ${{ steps.meta.outputs.tags }}
                push: true
    docker-backend:
        runs-on: ubuntu-latest
        steps:
            - name: Clonar repositorio
              uses: actions/checkout@v4
            - name: Iniciar sesión en Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Extraer metadatos
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: antarespadas/realworld-backend
            - name: Compilar y subir imagen
              uses: docker/build-push-action@v6
              with:
                context: ./backend
                tags: ${{ steps.meta.outputs.tags }}
                push: true
