name: Liberar y desplegar imágenes de Docker

on:
    release:
        types: [ published ]

jobs:
    docker-frontend:
        runs-on: ubuntu-latest
        steps:
            - name: Clonar repositorio
              uses: actions/checkout@v4
            - name: Iniciar sesión en Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Extraer metadatos
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: antarespadas/realworld-frontend
            - name: Compilar y subir imagen
              uses: docker/build-push-action@v6
              with:
                context: ./frontend
                tags: ${{ steps.meta.outputs.tags }}
                push: true
    docker-backend:
        runs-on: ubuntu-latest
        steps:
            - name: Clonar repositorio
              uses: actions/checkout@v4
            - name: Iniciar sesión en Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Extraer metadatos
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: antarespadas/realworld-backend
            - name: Compilar y subir imagen
              uses: docker/build-push-action@v6
              with:
                context: ./backend
                tags: ${{ steps.meta.outputs.tags }}
                push: true
    desplegar:
        runs-on: ubuntu-latest
        needs:
            - docker-frontend
            - docker-backend
        steps:
            # Conectarse al servidor por SSH
            # git clone repo
            # cd repo
            # docker compose pull
            # docker compose up -d
            - name: Conectarse al servidor por SSH
              uses: appleboy/ssh-action@v1
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USERNAME }}
                key: ${{ secrets.SSH_KEY }}
                script: |
                    if [ ! -d "realworld-antar" ]; then
                        git clone https://github.com/${{ github.repository }}.git -b ${{ github.ref_name }} realworld-antar
                    fi

                    cd realworld-antar

                    git fetch --tags
                    git switch --detach ${{ github.ref_name }}

                    docker compose pull
                    docker compose up -d